# absolute path to file listing active ticket txids
tickets_file_path: /path/to/ticket/list/file

# telegram bot token recieved from telegram.me/botfather
bot_token: 123456789:randomstringoflettersandsymbols

# chat(s) to send notifications to. can be single string or list of strings
chat_ids:
    - 12345678

# UTC OFFSET for funds availability estimate
utc_offset: 0

vote_eligibility: true

# delete old notification on next run
delete_old: true
